GET http://localhost:5007/games

###
GET http://localhost:5007/games/1
###
POST http://localhost:5007/games
Content-Type: application/json

{
    "name": "Test game",
    "genreId": 1,
    "price": 40.00,
    "releaseDay": "2013-01-01"
}

###

PUT http://localhost:5007/games/1
Content-Type: application/json

{
    "name": "GTA 5 Anhance",
    "genreId": 1,
    "price": 40.00,
    "releaseDay": "2015-01-01"
}

###

DELETE http://localhost:5007/games/3

###

GET http://localhost:5007/genres